name: Check radar Service
on:
  pull_request:
    branches:
      - master
    paths:
      - 'radar-service/**/*'
  push:
    branches:
<<<<<<< HEAD
      - master
    paths:
      - 'radar-service/**/*' 

env:
  ORG: knoldus Inc
  PROJECT_NAME: knoldus-leaderboard
  AUTHOR: MuZakkir Saifi(muzakkirsaifi123)

=======
      - master # the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
>>>>>>> parent of 8c90236 (adding github action)
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
<<<<<<< HEAD
          fetch-depth: 0 
          
=======
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
>>>>>>> parent of 8c90236 (adding github action)
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        working-directory: radar-service/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
        run: ./gradlew build sonar --info -Dsonar.projectKey=gradle-checks